name: cicd 

on:
  push: 
    branches: [ "registry" ]

  #workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    # checkout repository to github action runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0.4.0 
      with:
        workload_identity_provider:  'projects/908852839842/locations/global/workloadIdentityPools/roka-poc-github/providers/roka-access-quest'
        service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'
    - name: Replacing placholders
      run: |
          echo "*****replacing placeholders******"
          sed -i "s|\[PASSWORD\]|${{ env.TOKEN }}|g" *.tf
          cd Org_Template/terraform-google-cloud-artifact-registry

     # Terraform Init
    - name: Terraform Init
      run: |
        cd Org_Template/terraform-google-cloud-artifact-registry        
        terraform init --reconfigure
        #terraform init  -var="git_token=${{ secrets.token }}"

  validate: 
     runs-on: ubuntu-latest
     needs: init

     steps:
    # checkout repository to github action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0 
        with:
          workload_identity_provider:  'projects/908852839842/locations/global/workloadIdentityPools/roka-poc-github/providers/roka-access-quest'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'
      - name: Replacing placholders
        run: |
          echo "*****replacing placeholders******"
          sed -i "s|\[PASSWORD\]|${{ env.TOKEN }}|g" *.tf
          working-directory: ${{ env.WORKING_DIRECTORY }}
     
     #Terraform Validate
      - name: Terraform Validate
        run: |
         cd Org_Template/terraform-google-cloud-artifact-registry  
         terraform init
         terraform validate

  tflint:
    needs: validate
    uses: ./.github/workflows/lint.yaml
      

  plan: 
     runs-on: ubuntu-latest
     needs: tflint

     steps:
    # checkout repository to github action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0 
        with:
          workload_identity_provider:  'projects/908852839842/locations/global/workloadIdentityPools/roka-poc-github/providers/roka-access-quest'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'
      - name: Replacing placholders
        run: |
          echo "*****replacing placeholders******"
          sed -i "s|\[PASSWORD\]|${{ env.TOKEN }}|g" *.tf
          working-directory: ${{ env.WORKING_DIRECTORY }}

    # Terraform Plan
      - name: Terraform Plan
        run: |
          cd Org_Template/terraform-google-cloud-artifact-registry
          terraform init -reconfigure
          terraform plan --var-file=registry.tfvars -out=terraform.tfplan
          terraform apply -auto-approve -input=false terraform.tfplan
          terraform destroy -auto-approve 


