name: cicd  

on:
  push: 
    branches: [ "" ]

  #workflow_dispatch:
  pull_request:

permissions:
  contents: read
  id-token: 'write'

jobs:
  init:
    runs-on: ubuntu-latest

    steps:
    # checkout repository to github action runner
    - name: Checkout
      uses: actions/checkout@v3

    - id: auth
      uses: google-github-actions/auth@v0.4.0 
      with:
        workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/github-oidc/providers/github'
        service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'
   
    #- name: Authenticate to Google Cloud
     # uses: google-github-actions/auth@v0.4.0
     #env:
       # GOOGLE_CREDENTIALS: ${{ secrets.SA_KEY }}

     # Terraform Init
    - name: Terraform Init
      run: |
         cd Org_Template/terraform-google-cloud-folder
         terraform init --reconfigure \
          -backend-config="bucket=kd-project-quest-001" \
          -backend-config="prefix=org_module"" \
          -backend-config="project=kd-project-437712"
        #terraform init  -var="git_token=${{ secrets.token }}"

  validate: 
     runs-on: ubuntu-latest
     needs: init

     steps:
    # checkout repository to github action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0 
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/github-oidc/providers/github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'
     
     #Terraform Validate
      - name: Terraform Validate
        run: |
         cd Org_Template/terraform-google-cloud-folder
         terraform init
         terraform validate

  tflint:
    needs: validate
    uses: ./.github/workflows/lint.yaml
      

  plan_Apply: 
     runs-on: ubuntu-latest
     needs: tflint

     steps:
    # checkout repository to github action runner
      - name: Checkout
        uses: actions/checkout@v3

      - id: auth
        uses: google-github-actions/auth@v0.4.0 
        with:
          workload_identity_provider: 'projects/908852839842/locations/global/workloadIdentityPools/github-oidc/providers/github'
          service_account: 'inf-sa@seed-440521.iam.gserviceaccount.com'

    # Terraform Plan
      - name: Terraform Plan
        run: |
          cd Org_Template/terraform-google-cloud-folder
          terraform init -reconfigure
          terraform plan --var-file=folder.tfvars -out=terraform.tfplan
          terraform apply -auto-approve -input=false terraform.tfplan
          terraform destroy -auto-approve 

