name: 'Terraform Destroy'

on:
  workflow_dispatch:
    inputs:
      target_dir:
        description: 'Specify the subdirectory to destroy resources from (e.g.,compute , bucket, gke, database)'
        required: true
        default: ''

jobs:
  tf-destroy:
    runs-on: ubuntu-latest


    steps:
      - name: GIT Checkout
        uses: actions/checkout@v4
      - id: auth
        uses: google-github-actions/auth@v0.4.0  
        with:
           workload_identity_provider: ${{ secrets.WORKLOAD_IDENTITY_PROVIDER }}
           service_account: ${{ secrets.SERVICE_ACCOUNT_EMAIL }}

      - name: Terraform Init
        run: |
          cd ./dev/${{ github.event.inputs.target_dir }}
          terraform init

      - name: Terraform Destroy
        id: destroy
        run: |
          cd ./dev/${{ github.event.inputs.target_dir }}
          terraform destroy --auto-approve
